# Generated by Django 4.2.11 on 2024-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='price',
            field=models.DecimalField(decimal_places=10, default='23.23', max_digits=19),
            preserve_default=False,
        ),
    ]
