# Generated by Django 4.2.11 on 2024-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
