# Generated by Django 4.2.11 on 2024-05-22 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_alter_folder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 1, 25, 0, 811670, tzinfo=datetime.timezone.utc)),
        ),
    ]
