# Generated by Django 4.2.11 on 2024-05-22 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_folder_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 1, 25, 40, 524227, tzinfo=datetime.timezone.utc)),
        ),
    ]
