# Generated by Django 4.2.11 on 2024-05-23 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folder_expires_at_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 2, 38, 9, 71468, tzinfo=datetime.timezone.utc)),
        ),
    ]
