# Generated by Django 4.2.11 on 2024-05-23 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0007_alter_folder_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='images',
        ),
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 5, 59, 11, 543852, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_uploaded')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='folders.uploadimage')),
            ],
        ),
    ]
