# Generated by Django 4.2.11 on 2024-05-25 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_image_date_added_alter_folder_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default='2023-12-12', upload_to='images_uploaded'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 1, 32, 28, 911321, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
