# Generated by Django 4.2.11 on 2024-05-25 07:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folders', '0010_uploadimage_image_alter_folder_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='UploadFile',
        ),
        migrations.AlterField(
            model_name='folder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 7, 23, 7, 586930, tzinfo=datetime.timezone.utc)),
        ),
    ]
